Models:
  ElasticNet:
    alpha: 0.2
    l1_ratio: 0.1
    random_state: 42

  LinearRegression: {}  

  Ridge:
    alpha: 1.0
    random_state: 42

  Lasso:
    alpha: 0.1
    random_state: 42

  RandomForest:
    n_estimators: 100
    max_depth: 10
    random_state: 42

  GradientBoosting:
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 42
